export const authCopy = {
  login: {
    title: "Welcome to Anthiel",
    emailSubtitle: "We'll email you a sign-in link",
    usernameSubtitle: "Sign in with your username and password",
    emailLabel: "Email",
    emailPlaceholder: "you@company.com",
    emailRequired: "Email is required",
    emailInvalid: "Enter a valid email",
    sendLink: "Email sign-in link",
    sentTitle: "Check your email",
    sentDescription: "If an account exists for {email}, we sent a sign-in link.",
    sendAnother: "Use a different email",
    staffSignIn: "Sign in with username",
    emailSignIn: "Sign in with email",
    usernameLabel: "Username",
    passwordLabel: "Password",
    usernameRequired: "Username is required",
    passwordRequired: "Password is required",
    usernamePlaceholder: "username",
    submit: "Login",
    sendFailed: "Unable to send sign-in link",
    signInFailed: "Unable to sign in",
    linkInvalid: "This sign-in link is invalid or expired. Request a new one.",
  },
} as const;
