/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardUsersRouteImport } from './routes/_authenticated/dashboard/users'
import { Route as AuthenticatedDashboardRolesRouteImport } from './routes/_authenticated/dashboard/roles'
import { Route as AuthenticatedDashboardPermissionsRouteImport } from './routes/_authenticated/dashboard/permissions'
import { Route as AuthenticatedDashboardInvoicesRouteImport } from './routes/_authenticated/dashboard/invoices'
import { Route as GuestDashboardAuthLoginRouteImport } from './routes/_guest/dashboard/auth/login'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardUsersRoute =
  AuthenticatedDashboardUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardRolesRoute =
  AuthenticatedDashboardRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardPermissionsRoute =
  AuthenticatedDashboardPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardInvoicesRoute =
  AuthenticatedDashboardInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const GuestDashboardAuthLoginRoute = GuestDashboardAuthLoginRouteImport.update({
  id: '/dashboard/auth/login',
  path: '/dashboard/auth/login',
  getParentRoute: () => GuestRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/dashboard/invoices': typeof AuthenticatedDashboardInvoicesRoute
  '/dashboard/permissions': typeof AuthenticatedDashboardPermissionsRoute
  '/dashboard/roles': typeof AuthenticatedDashboardRolesRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/auth/login': typeof GuestDashboardAuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/dashboard/invoices': typeof AuthenticatedDashboardInvoicesRoute
  '/dashboard/permissions': typeof AuthenticatedDashboardPermissionsRoute
  '/dashboard/roles': typeof AuthenticatedDashboardRolesRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/auth/login': typeof GuestDashboardAuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/dashboard/invoices': typeof AuthenticatedDashboardInvoicesRoute
  '/_authenticated/dashboard/permissions': typeof AuthenticatedDashboardPermissionsRoute
  '/_authenticated/dashboard/roles': typeof AuthenticatedDashboardRolesRoute
  '/_authenticated/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_guest/dashboard/auth/login': typeof GuestDashboardAuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/invoices'
    | '/dashboard/permissions'
    | '/dashboard/roles'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/invoices'
    | '/dashboard/permissions'
    | '/dashboard/roles'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/auth/login'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_guest'
    | '/_authenticated/dashboard'
    | '/_authenticated/'
    | '/_authenticated/dashboard/invoices'
    | '/_authenticated/dashboard/permissions'
    | '/_authenticated/dashboard/roles'
    | '/_authenticated/dashboard/users'
    | '/_authenticated/dashboard/'
    | '/_guest/dashboard/auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/users': {
      id: '/_authenticated/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AuthenticatedDashboardUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/roles': {
      id: '/_authenticated/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof AuthenticatedDashboardRolesRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/permissions': {
      id: '/_authenticated/dashboard/permissions'
      path: '/permissions'
      fullPath: '/dashboard/permissions'
      preLoaderRoute: typeof AuthenticatedDashboardPermissionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/invoices': {
      id: '/_authenticated/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof AuthenticatedDashboardInvoicesRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_guest/dashboard/auth/login': {
      id: '/_guest/dashboard/auth/login'
      path: '/dashboard/auth/login'
      fullPath: '/dashboard/auth/login'
      preLoaderRoute: typeof GuestDashboardAuthLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardInvoicesRoute: typeof AuthenticatedDashboardInvoicesRoute
  AuthenticatedDashboardPermissionsRoute: typeof AuthenticatedDashboardPermissionsRoute
  AuthenticatedDashboardRolesRoute: typeof AuthenticatedDashboardRolesRoute
  AuthenticatedDashboardUsersRoute: typeof AuthenticatedDashboardUsersRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardInvoicesRoute: AuthenticatedDashboardInvoicesRoute,
    AuthenticatedDashboardPermissionsRoute:
      AuthenticatedDashboardPermissionsRoute,
    AuthenticatedDashboardRolesRoute: AuthenticatedDashboardRolesRoute,
    AuthenticatedDashboardUsersRoute: AuthenticatedDashboardUsersRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface GuestRouteRouteChildren {
  GuestDashboardAuthLoginRoute: typeof GuestDashboardAuthLoginRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestDashboardAuthLoginRoute: GuestDashboardAuthLoginRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
