/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as Char123LocaleChar125BlogSlugRouteImport } from "./routes/{-$locale}/blog/$slug";
import { Route as Char123LocaleChar125BlogIndexRouteImport } from "./routes/{-$locale}/blog/index";
import { Route as Char123LocaleChar125IndexRouteImport } from "./routes/{-$locale}/index";

const Char123LocaleChar125IndexRoute = Char123LocaleChar125IndexRouteImport.update({
  id: "/{-$locale}/",
  path: "/{-$locale}/",
  getParentRoute: () => rootRouteImport,
} as any);
const Char123LocaleChar125BlogIndexRoute = Char123LocaleChar125BlogIndexRouteImport.update({
  id: "/{-$locale}/blog/",
  path: "/{-$locale}/blog/",
  getParentRoute: () => rootRouteImport,
} as any);
const Char123LocaleChar125BlogSlugRoute = Char123LocaleChar125BlogSlugRouteImport.update({
  id: "/{-$locale}/blog/$slug",
  path: "/{-$locale}/blog/$slug",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/{-$locale}/": typeof Char123LocaleChar125IndexRoute;
  "/{-$locale}/blog/$slug": typeof Char123LocaleChar125BlogSlugRoute;
  "/{-$locale}/blog/": typeof Char123LocaleChar125BlogIndexRoute;
}
export interface FileRoutesByTo {
  "/{-$locale}": typeof Char123LocaleChar125IndexRoute;
  "/{-$locale}/blog/$slug": typeof Char123LocaleChar125BlogSlugRoute;
  "/{-$locale}/blog": typeof Char123LocaleChar125BlogIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/{-$locale}/": typeof Char123LocaleChar125IndexRoute;
  "/{-$locale}/blog/$slug": typeof Char123LocaleChar125BlogSlugRoute;
  "/{-$locale}/blog/": typeof Char123LocaleChar125BlogIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/{-$locale}/" | "/{-$locale}/blog/$slug" | "/{-$locale}/blog/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/{-$locale}" | "/{-$locale}/blog/$slug" | "/{-$locale}/blog";
  id: "__root__" | "/{-$locale}/" | "/{-$locale}/blog/$slug" | "/{-$locale}/blog/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute;
  Char123LocaleChar125BlogSlugRoute: typeof Char123LocaleChar125BlogSlugRoute;
  Char123LocaleChar125BlogIndexRoute: typeof Char123LocaleChar125BlogIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/{-$locale}/": {
      id: "/{-$locale}/";
      path: "/{-$locale}";
      fullPath: "/{-$locale}/";
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/{-$locale}/blog/": {
      id: "/{-$locale}/blog/";
      path: "/{-$locale}/blog";
      fullPath: "/{-$locale}/blog/";
      preLoaderRoute: typeof Char123LocaleChar125BlogIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/{-$locale}/blog/$slug": {
      id: "/{-$locale}/blog/$slug";
      path: "/{-$locale}/blog/$slug";
      fullPath: "/{-$locale}/blog/$slug";
      preLoaderRoute: typeof Char123LocaleChar125BlogSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125BlogSlugRoute: Char123LocaleChar125BlogSlugRoute,
  Char123LocaleChar125BlogIndexRoute: Char123LocaleChar125BlogIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";

import type { getRouter } from "./router.tsx";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
